package org.kbroman.android.polarpvc2

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.kbroman.android.polarpvc2.ecg.EcgDetect
import org.kbroman.android.polarpvc2.ecg.EcgFeatures
import kotlin.math.abs

/**
 * Cross-language parity: the Kotlin detect/features/classify ports must agree
 * with the offline Python pipeline on a shared golden fixture
 * (app/src/test/resources/parity/, generated by
 * analysis/scripts/make_parity_fixture.py). Guards against silent drift between
 * the live preview and the validated offline burden source.
 */
class EcgParityTest {

    private val fs = 130.0

    private fun resource(name: String): List<String> {
        val url = javaClass.classLoader?.getResourceAsStream(name)
            ?: throw IllegalStateException("missing test resource: $name")
        return url.bufferedReader().readLines()
    }

    // --- filtfilt vs scipy ---

    @Test
    fun filtfilt_matches_scipy_golden() {
        val lines = resource("parity/filter_golden.csv")
        val x = ArrayList<Double>()
        val y1 = ArrayList<Double>(); val y2 = ArrayList<Double>(); val y3 = ArrayList<Double>()
        for (line in lines.drop(1)) {
            val p = line.split(",")
            x.add(p[0].toDouble()); y1.add(p[1].toDouble()); y2.add(p[2].toDouble()); y3.add(p[3].toDouble())
        }
        val xa = x.toDoubleArray()
        assertMaxDiff(EcgDetect.filtfilt(EcgDetect.BP_5_15, xa), y1.toDoubleArray(), 1e-6, "BP_5_15")
        assertMaxDiff(EcgDetect.filtfilt(EcgDetect.BP_5_25, xa), y2.toDoubleArray(), 1e-6, "BP_5_25")
        assertMaxDiff(EcgDetect.filtfilt(EcgDetect.BP_0p5_25, xa), y3.toDoubleArray(), 1e-6, "BP_0p5_25")
    }

    private fun assertMaxDiff(a: DoubleArray, b: DoubleArray, tol: Double, label: String) {
        assertEquals("$label length", b.size, a.size)
        var maxd = 0.0
        for (i in a.indices) maxd = maxOf(maxd, abs(a[i] - b[i]))
        assertTrue("$label max abs diff $maxd > $tol", maxd <= tol)
    }

    // --- full pipeline (batch) vs Python labels ---

    private data class Ecg(val mv: DoubleArray, val t: DoubleArray, val tNs: LongArray)

    private fun loadEcg(): Ecg {
        val lines = resource("parity/ecg_mock.csv")
        val mv = ArrayList<Double>(); val t = ArrayList<Double>(); val tNs = ArrayList<Long>()
        for (line in lines) {
            if (line.startsWith("#") || line.startsWith("time")) continue
            if (line.isBlank()) continue
            val p = line.split(",")
            val ns = p[0].toLong()
            tNs.add(ns); t.add(ns / 1e9); mv.add(p[1].toDouble() / 1000.0)
        }
        return Ecg(mv.toDoubleArray(), t.toDoubleArray(), tNs.toLongArray())
    }

    private data class Lab(val idx: Int, val isPvc: Boolean, val isArtifact: Boolean, val corr: Double, val noise: Double)

    private fun loadLabels(): List<Lab> {
        val lines = resource("parity/labels.csv")
        return lines.drop(1).filter { it.isNotBlank() }.map {
            val p = it.split(",")
            Lab(p[0].toInt(), p[2] == "1", p[3] == "1", p[5].toDouble(), p[7].toDouble())
        }
    }

    @Test
    fun pipeline_matches_python_labels() {
        val ecg = loadEcg()
        val beats = EcgDetect.detectBeats(ecg.mv, fs)
        val feats = EcgFeatures.extractFeatures(ecg.mv, ecg.t, beats, fs)
        val labels = PVCClassifier.classifyBeats(feats)
        val expected = loadLabels()

        // detection agreement (Jaccard on sample indices)
        val kSet = beats.toHashSet()
        val eSet = expected.map { it.idx }.toHashSet()
        val inter = kSet.count { it in eSet }
        val union = (kSet + eSet).size
        val detAgree = inter.toDouble() / union
        assertTrue("detection agreement $detAgree < 0.98", detAgree >= 0.98)

        // per-beat label agreement on beats present in both
        val kByIdx = feats.indices.associate { feats[it].index to labels[it] }
        var matched = 0; var pvcAgree = 0; var artAgree = 0
        var kBurdenNum = 0; var kBurdenDen = 0
        for (e in expected) {
            val lab = kByIdx[e.idx] ?: continue
            matched++
            if (lab.isPvc == e.isPvc) pvcAgree++
            if (lab.isArtifact == e.isArtifact) artAgree++
            // feature closeness
            val f = feats.first { it.index == e.idx }
            assertTrue("corr drift at ${e.idx}: ${f.templateCorr} vs ${e.corr}", abs(f.templateCorr - e.corr) <= 1e-3)
            assertTrue("noise drift at ${e.idx}: ${f.noiseRatio} vs ${e.noise}", abs(f.noiseRatio - e.noise) <= 1e-3)
        }
        val pvcRate = pvcAgree.toDouble() / matched
        val artRate = artAgree.toDouble() / matched
        assertTrue("PVC-label agreement $pvcRate < 0.95", pvcRate >= 0.95)
        assertTrue("artifact-label agreement $artRate < 0.95", artRate >= 0.95)

        // burden within 1 percentage point
        for (lab in labels) if (!lab.isArtifact) { kBurdenDen++; if (lab.isPvc) kBurdenNum++ }
        val kBurden = 100.0 * kBurdenNum / kBurdenDen
        val eNum = expected.count { it.isPvc }
        val eDen = expected.count { !it.isArtifact }
        val eBurden = 100.0 * eNum / eDen
        assertTrue("burden drift: $kBurden vs $eBurden", abs(kBurden - eBurden) <= 1.0)
    }

    // --- streaming wrapper vs batch ---

    private class CollectingListener : EcgListener {
        val pvcTimes = ArrayList<Double>()
        val peakTimes = ArrayList<Double>()
        override fun onEcgSample(timeSec: Double, voltage: Double) {}
        override fun onEcgBatchDone() {}
        override fun onPeak(timeSec: Double, voltage: Double) { peakTimes.add(timeSec) }
        override fun onPeakReplaced(timeSec: Double, voltage: Double) {}
        override fun onPvc(timeSec: Double, voltage: Double) { pvcTimes.add(timeSec) }
        override fun onStats(hrBpm: Double, pvcAvePct: Double, pvcTotalPct: Double?, rrLastTimeSec: Double, pvcLastTimeSec: Double, enoughForPlot: Boolean) {}
        override fun onConnectionChanged(connected: Boolean, deviceId: String) {}
        override fun onBatteryLevel(level: Int) {}
        override fun onRecordingChanged(recording: Boolean) {}
    }

    @Test
    fun streaming_matches_batch() {
        val ecg = loadEcg()
        // batch reference PVC times
        val beats = EcgDetect.detectBeats(ecg.mv, fs)
        val feats = EcgFeatures.extractFeatures(ecg.mv, ecg.t, beats, fs)
        val labels = PVCClassifier.classifyBeats(feats)
        val batchPvcTimes = feats.indices.filter { labels[it].isPvc }.map { feats[it].t }
        val endTime = ecg.t.last()

        // feed in ~Polar-sized batches through the streaming wrapper
        val listener = CollectingListener()
        val pd = PeakDetection(listener)
        val batch = 70
        var i = 0
        while (i < ecg.mv.size) {
            val hi = minOf(i + batch, ecg.mv.size)
            pd.ingestBatch(ecg.tNs.copyOfRange(i, hi), ecg.mv.copyOfRange(i, hi))
            i = hi
        }

        // every streaming PVC must match a batch PVC (no spurious live PVCs);
        // streaming won't finalize the last ~4 s, so compare against batch PVCs
        // up to (end - 4 s)
        val cutoff = endTime - 4.0
        val expectedLive = batchPvcTimes.filter { it <= cutoff }
        var spurious = 0
        for (pt in listener.pvcTimes) {
            if (batchPvcTimes.none { abs(it - pt) < 0.05 }) spurious++
        }
        assertTrue("streaming produced $spurious spurious PVCs", spurious <= 1)
        // and it should catch most of the finalizable PVCs
        var caught = 0
        for (et in expectedLive) if (listener.pvcTimes.any { abs(it - et) < 0.05 }) caught++
        val recall = if (expectedLive.isEmpty()) 1.0 else caught.toDouble() / expectedLive.size
        assertTrue("streaming PVC recall $recall < 0.85", recall >= 0.85)
        assertTrue("streaming finalized no beats", pd.totalBeats > 0)
    }
}
